# Generated by Django 5.1 on 2024-11-30 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt_processor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='item',
            name='short_description',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.CreateModel(
            name='ItemsOnReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receipt_processor.item')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receipt_processor.receipt')),
            ],
        ),
        migrations.AlterField(
            model_name='receipt',
            name='items',
            field=models.ManyToManyField(through='receipt_processor.ItemsOnReceipt', to='receipt_processor.item'),
        ),
        migrations.DeleteModel(
            name='ReceiptInfo',
        ),
    ]
