# Generated by Django 5.1 on 2024-11-30 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipt_processor', '0002_item_price_item_short_description_itemsonreceipt_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemsOnReceipt',
            new_name='ItemAssignmentToReceipt',
        ),
    ]
