# Generated by Django 5.1 on 2024-11-30 19:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt_processor', '0006_receipt_points_delete_receiptpoints'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='purchase_datetime',
        ),
        migrations.AddField(
            model_name='receipt',
            name='purchase_date',
            field=models.DateField(default=datetime.datetime(2024, 11, 30, 14, 44, 2, 405142)),
        ),
        migrations.AddField(
            model_name='receipt',
            name='purchase_time',
            field=models.TimeField(default=datetime.time(14, 44, 2, 405142)),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='points',
            field=models.BigIntegerField(default=0),
        ),
    ]
