# Generated by Django 5.1 on 2024-11-30 22:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt_processor', '0007_remove_receipt_purchase_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='purchase_date',
            field=models.DateField(default=datetime.datetime(2024, 11, 30, 17, 6, 28, 107882)),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='purchase_time',
            field=models.TimeField(default=datetime.time(17, 6, 28, 107881)),
        ),
    ]
